// <auto-generated />
namespace IdentitySample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-beta2-31111")]
    public sealed partial class Frame : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Frame));
        
        string IMigrationMetadata.Id
        {
            get { return "201412111313307_Frame"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
