// <auto-generated />
namespace IdentitySample.Migrations.MyDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-beta2-31111")]
    public sealed partial class Messages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Messages));
        
        string IMigrationMetadata.Id
        {
            get { return "201412301358237_Messages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
